### PR TITLE
Added Ability To Push to Maven Central

### PR DESCRIPTION
**Pull request by AndrewReitz**
Copy the gradle.properties.dist to gradle.properties and fill in the fields.  Run ./gradlew uploadArchives -Prelease to push to release, -Psnapshot to release to snapshots.

Also clean up build.gradle and added Travis Builds

### CODE REVIEW

**Comment by davidgyoung** [comment]
Thanks, Andrew.  When I try doing a build, I get the error below.  Any ideas?  Thanks, David

$ gradle build

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'AndroidIBeaconLibrary'.
  
  > Could not resolve all dependencies for configuration ':_debugTestCompile'.
  > Could not find any version that matches com.android.support:support-v4:19.1.+.
  >  Required by:
  >      com.radiusnetworks:AndroidIBeaconLibrary:0.7.6 > com.squareup:fest-android:1.0.8
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.963 secs

**Comment by AndrewReitz** [comment]
It looks like your support library needs to be updated. Can you open up the sdk manager and see if there is a newer version?

**Comment by davidgyoung** [comment]
That did it.  Something didn't like me being one dot version behind.  So now I can do a `./gradlew release` successfully, but I don't think it tries to sign or upload to maven central.  Should this work a different way?

**Comment by AndrewReitz** [comment]
The `release` task is an artifact from what was there before. It looks like it's suppose to generate the eclipse build. I can add the upload task to that if you would like. Currently to upload it's `./gradlew uploadArchives -Prelease`, to do a release `./gradlew uploadArchives -Psnapshot` for snapshot, and `./gradlew uploadArchives` for local.

**Comment by AndrewReitz** [comment]
I just updated to have the version to generate based off of the latest tag. Also updated so when you run `./gradlew release` a complete release should be done. Also added `mavenRelease` and `mavenSnapshot`, which do the same things as `uploadArchives -Psnapshot` and `uploadArchives -Prelease`

**Comment by AndrewReitz** [comment]
Oh also moved the group to gradle.properties so that I can have it go to my snapshot when testing, without having to worry about checking in something wrong.

**Comment by AndrewReitz** [comment]
@davidgyoung What's the status on this? It looks like it's been merged in.

**Comment by davidgyoung** [comment]
Merged in e353fb2c6338e72b4d23f8f78a1247921b29f92a

**Pull request closed without merging**
